### PR TITLE
adding test suite (plz merge when ready)

### PR DESCRIPTION
**Pull request by McCloudFace**
- [x] Add unit tests for db
- [x] Comment db methods & tests
- [x] Investigate express tests, best practices for assertions
- [x] Add unit tests for server

### CODE REVIEW

**Comment by McCloudFace** [comment]
ready for review, and merge if appropriate. Thanks.

**Comment by McCloudFace** [comment]
@MengRS or @weber93 if one of you could review this PR when you have a chance, that would be super swell.

**Review by mweber-ak — APPROVED** [review]
Looks good! My only comment is on the db.getAtrail that the name is a little hard to read and might be better as getTrail since it already implies it gets a single trail.

**Comment by McCloudFace** [comment]
Thanks Matt!

**Pull request merged**
